services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: khajit03/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb:
    build: ./mongodb
    image: khajit03/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db #search the docker hub for -v to get where the data is getting stored
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: khajit03/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes: #-v rabbitmq:/var/lib/rabbitmq
    - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  user:
    build: ./user
    image: khajit03/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    build: ./cart
    image: khajit03/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: khajit03/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  payment:
    build: ./payment
    image: khajit03/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - user
    - cart
  frontend:
    build: ./frontend
    image: khajit03/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - payment
    - cart
    - shipping
    - user
networks:
  default:
    driver: bridge
    name: roboshop
    external: false #true if u created network using docker network command
volumes:
  #docker volume create mongodb
  mysql: 
  redis:
  mongodb:
  rabbitmq: