#this is multi stage build
FROM node:20.19.5-alpine3.22 AS build
WORKDIR /opt/server
COPY package.json .
COPY *.js .
#this may add extra cache memory
RUN npm install


FROM node:20.19.5-alpine3.22
#create a group or user
WORKDIR /opt/server
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop  && \
   chown -R roboshop:roboshop /opt/server
EXPOSE 8080
LABEL com.project="roboshop" \
component="cart"  \
created_by="tsword03"
ENV REDIS_HOST="redis" \
    CATALOGUE_HOST="catalogue" \
    CATALOGUE_PORT="8080"
USER roboshop
COPY --from=build --chown=roboshop:roboshop /opt/server /opt/server
CMD ["server.js"]    
ENTRYPOINT ["node"]



# FROM node:20
# WORKDIR /opt/server
# EXPOSE 8080
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV REDIS_HOST="redis" \
#     CATALOGUE_HOST="catalogue" \
#     CATALOGUE_PORT="8080"
# CMD ["node","server.js"]    