#this is multi stage build
FROM node:20.19.5-alpine3.22 AS build
WORKDIR /opt/server
COPY package.json .
COPY *.js .
#this may add extra cache memory
RUN npm install


FROM node:20.19.5-alpine3.22
#create a group or user
WORKDIR /opt/server
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop  && \
   chown -R roboshop:roboshop /opt/server
EXPOSE 8080
LABEL com.project="roboshop" \
component="catalogue"  \
created_by="tsword03"
ENV MONGO="true" \
MONGO_URL="mongodb://mongodb:27017/catalogue"
USER roboshop
COPY --from=build --chown=roboshop:roboshop /opt/server /opt/server
CMD ["server.js"]    
ENTRYPOINT ["node"]


#second iteration reducing the base image
# FROM node:20.19.5-alpine3.22
# WORKDIR /opt/server
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV MONGO="true" \
#     MONGO_URL="mongodb://mongodb:27017/catalogue"
# CMD ["node","server.js"]    

#first iteration
# FROM node:20
# WORKDIR /opt/server
# COPY package.json .
# COPY *.js .
# RUN npm install
# ENV MONGO="true" \
#     MONGO_URL="mongodb://mongodb:27017/catalogue"
# CMD ["node","server.js"]    